### ISSUE TITLE
7

### ISSUE THREAD

**Issue by emptyb** [Beast22/beast22.github.io#7]
https://monosnap.com/file/T08wxmlvXDCGQ5J7eTAjUZK8mORWOO

**Comment by Beast22** [comment]
можно скрин сам прислать, я не могу по ссылке попасть

> Четверг, 17 декабря 2015, 2:23 -08:00 от emptyb notifications@github.com:
> 
> https://monosnapcom/file/T08wxmlvXDCGQ5J7eTAjUZK8mORWOO
> —
> Reply to this email directly or  view it on GitHub .

## 

С уважением, Евгений.

**Comment by emptyb** [comment]
https://monosnap.com/file/ERQ1eF8jJ5Uhg3ILcywTgs322NA50V
https://monosnap.com/file/km08nQSpR0fybyswTMkYqrYkMvNqoZ
https://monosnap.com/file/OYlfar9xFW9h8gwnBElFgKNBzXjJvh
https://monosnap.com/file/wlwnl2TzsXVQTyUQybzOKPf1W6Vrft
